### PR TITLE
Add go-fuzz test

### PR DESCRIPTION
**Pull request by pkillarjun**
Adding [go-fuzz](https://go.dev/doc/security/fuzz/) tests for [oss-fuzz](https://github.com/google/oss-fuzz) integration.

### CODE REVIEW

**Comment by armfazh** [comment]
this is great. Could you please add these fuzz tests to the CI script? Maybe running them for few seconds. So, we are sure tests are compiling and running.

**Comment by pkillarjun** [comment]
> this is great. Could you please add these fuzz tests to the CI script? Maybe running them for few seconds. So, we are sure tests are compiling and running.


I have a better idea, and this is my plan.

1. Merge this PR. We can probably remove the `FUZZING.md`, but I think it's important.
2. Add `roughtime` to the [oss-fuzz](https://google.github.io/oss-fuzz/) fuzzing infrastructure, like [circl](https://github.com/google/oss-fuzz/tree/master/projects/circl) from `cloudflare`.
3. Then, we add the [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/). It will do the same as what you are requesting for.

**Comment by armfazh** [comment]
I agree with the plan, please go forward.

**Comment by pkillarjun** [comment]
> I agree with the plan, please go forward.

Alright;

I need a bit of help. I have no idea how I can reproduce these errors in my local environment.

```bash
$ golangci-lint run protocol/
# I see nothing.
```

**Comment by armfazh** [comment]
This is an issue caused by golangci-lint, since it was compiled with a different version of Go. Because of that, it does not recognize new language features. The solution is to compile golangci-lint with the same version Go version (which explains why locally it works).

Add this line to the workflow
```diff
 uses: golangci/golangci-lint-action@v6
 with:
   version: v1.61.0
+  install-mode: goinstall
```

Similarly to [this one](https://github.com/cloudflare/circl/blob/main/.github/workflows/ci-actions.yml#L28).

**Comment by pkillarjun** [comment]
I am not so sure whether this patch https://github.com/cloudflare/roughtime/pull/65/commits/4543e4caf7886a60a1efebe0165bbfa2969159ae will work or not

**Review by armfazh — APPROVED** [review]

**Pull request merged**
