### PR TITLE
protocol should't be specified in go.mod

### PR DESCRIPTION
**Pull request by VadimInshakov**
go.mod fixed

### CODE REVIEW

**Comment by VadimInshakov** [comment]
Is anybody here? :)

**Comment by armfazh** [comment]
It seems correct, also make sure to update `go.sum` file too.

**Comment by wbl** [comment]
I don't think the go.sum will change from this necessarily?

**Comment by VadimInshakov** [comment]
> It seems correct, also make sure to update `go.sum` file too.

Ok, done.

**Pull request merged**
